FROM python:3.12.1
  ENV PYTHONDONTWRITEBYTECODE 1
  ENV PYTHONUNBUFFERED 1

  RUN apt-get update \
    && apt-get install -y postgresql-client \
    && rm -rf /var/lib/apt/lists/*

  RUN mkdir /app
  WORKDIR /app
  RUN pip install --upgrade pip
  COPY requirements.txt .
  RUN pip install -r requirements.txt
  COPY . /app

  # RUN python manage.py migrate

  # RUN apt-get update && apt-get install -y postgresql-client

  # COPY scripts/populate_db.sql /app/scripts/
  # RUN psql -U postgres -d conexaopet_db -a -f /app/scripts/populate_db.sql

  ENV PYTHONPATH=/app