
version: '3.7'

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile.dev
    container_name: conexaopet_web
    command: >
      sh -c "python manage.py migrate && gunicorn conexaopet.wsgi:application --bind 0.0.0.0:8000"
    volumes:
      - .:/app/
      - staticfiles:/app/media
      - ./media:/app/media
    expose:
      - 8000
    env_file:
      - ./.env
    depends_on:
      - db

  db:
    image: postgres:15.6
    container_name: conexaopet_db
    volumes:
      - postgres_data:/var/lib/conexaopet-api_postgres_data/data/ 
      - ./scripts/populate_db.sql:/populate_db.sql
    environment:
      - POSTGRES_DB=conexaopet_db
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    env_file:
      - ./.env
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "postgres"]
      interval: 10s
      timeout: 5s
      retries: 3

  populate_db:
    image: postgres:15.6
    volumes:
      - ./scripts/:/scripts
    command: >
      sh -c "sleep 5 && PGPASSWORD=postgres psql -U postgres -h db -d conexaopet_db -a -f /scripts/populate_db.sql"
    depends_on:
      db:
        condition: service_healthy

  nginx:
    build:
      context: ./nginx
      dockerfile: Dockerfile.dev
    container_name: conexaopet_nginx
    volumes:
      - staticfiles:/app/media
      - ./media:/app/media
    ports:
      - 8008:80
    depends_on:
      - web

volumes:
  postgres_data:
  staticfiles:
