version: '3.7'
services:
  nginx:
    container_name: coexaopet_web
    restart: on-failure
    image: nginx:1.25.4
    environment:
      - EC2_HOST_DNS=${EC2_HOST_DNS}
      - SECRET_KEY=${SECRET_KEY}
      - DEBUG=${DEBUG}
      - DB_ENGINE=${DB_ENGINE}
      - DB_NAME=${DB_NAME}
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_HOST=${DB_HOST}
      - DB_PORT=${DB_PORT}
      - EMAIL_HOST_USER=${EMAIL_HOST_USER}
      - EMAIL_HOST_PASSWORD=${EMAIL_HOST_PASSWORD}
    env_file:
      - .env
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
      - static_volume:/srv/app/static
    ports:
      - "80:80"
    depends_on:
      - web

  web:
    container_name: conexaopet_app
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    environment:
      - EC2_HOST_DNS=${EC2_HOST_DNS}
      - SECRET_KEY=${SECRET_KEY}
      - DEBUG=${DEBUG}
      - DB_ENGINE=${DB_ENGINE}
      - DB_NAME=${DB_NAME}
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_HOST=${DB_HOST}
      - DB_PORT=${DB_PORT}
      - EMAIL_HOST_USER=${EMAIL_HOST_USER}
      - EMAIL_HOST_PASSWORD=${EMAIL_HOST_PASSWORD}
    env_file:
      - .env
    ports:
      - "5000:5000"
    command: >
      sh -c " python manage.py migrate && python manage.py runserver 0.0.0.0:5000"
    volumes:
     - .:/srv/app
     - static_volume:/srv/app/static
    depends_on:
     - db
  db:
    container_name: conexaopet_db
    image: postgres:15.6
    environment:
      - EC2_HOST_DNS=${EC2_HOST_DNS}
      - SECRET_KEY=${SECRET_KEY}
      - DEBUG=${DEBUG}
      - DB_ENGINE=${DB_ENGINE}
      - DB_NAME=${DB_NAME}
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_HOST=${DB_HOST}
      - DB_PORT=${DB_PORT}
      - EMAIL_HOST_USER=${EMAIL_HOST_USER}
      - EMAIL_HOST_PASSWORD=${EMAIL_HOST_PASSWORD}
    env_file:
      - .env
    volumes:
      - postgres_data:/var/lib/postgresql/data/
      - ./scripts:/docker-entrypoint-initdb.d
      - .:/srv/app
    command: >
      sh -c "docker-entrypoint.sh postgres & /bin/bash /srv/app/scripts/startup.sh"

volumes:
  static_volume:
  postgres_data: