version: '3.7'

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: conexaopet_web
    environment:
      - EC2_HOST_DNS=${EC2_HOST_DNS}
      - SECRET_KEY=${SECRET_KEY}
      - DEBUG=${DEBUG}
      - DB_ENGINE=${DB_ENGINE}
      - DB_NAME=${DB_NAME}
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_HOST=${DB_HOST}
      - DB_PORT=${DB_PORT}
      - EMAIL_HOST_USER=${EMAIL_HOST_USER}
      - EMAIL_HOST_PASSWORD=${EMAIL_HOST_PASSWORD}
    command: >
      sh -c "python manage.py migrate && gunicorn conexaopet.wsgi:application --bind 0.0.0.0:8000"
    volumes:
      - .:/app/
      - staticfiles:/app/media
      - ./media:/app/media
    expose:
      - 8000
    env_file:
      - ./.env
    depends_on:
      - db

  db:
    image: postgres:15.6
    container_name: conexaopet_db
    environment:
      - EC2_HOST_DNS=${EC2_HOST_DNS}
      - SECRET_KEY=${SECRET_KEY}
      - DEBUG=${DEBUG}
      - DB_ENGINE=${DB_ENGINE}
      - DB_NAME=${DB_NAME}
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_HOST=${DB_HOST}
      - DB_PORT=${DB_PORT}
      - EMAIL_HOST_USER=${EMAIL_HOST_USER}
      - EMAIL_HOST_PASSWORD=${EMAIL_HOST_PASSWORD}
      - POSTGRES_DB=conexaopet_db
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    volumes:
      - postgres_data:/var/lib/conexaopet-api_postgres_data/data/ 
      - ./scripts/populate_db.sql:/populate_db.sql
    env_file:
      - ./.env
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "postgres"]
      interval: 10s
      timeout: 5s
      retries: 3

  populate_db:
    image: postgres:15.6
    volumes:
      - ./scripts/:/scripts
    command: >
      sh -c "sleep 5 && PGPASSWORD=postgres psql -U postgres -h db -d conexaopet_db -a -f /scripts/populate_db.sql"
    depends_on:
      db:
        condition: service_healthy

  nginx:
    container_name: conexaopet_nginx
    build:
      context: ./nginx
      dockerfile: Dockerfile
    environment:
      - EC2_HOST_DNS=${EC2_HOST_DNS}
      - SECRET_KEY=${SECRET_KEY}
      - DEBUG=${DEBUG}
      - DB_ENGINE=${DB_ENGINE}
      - DB_NAME=${DB_NAME}
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_HOST=${DB_HOST}
      - DB_PORT=${DB_PORT}
      - EMAIL_HOST_USER=${EMAIL_HOST_USER}
      - EMAIL_HOST_PASSWORD=${EMAIL_HOST_PASSWORD}
    env_file:
      - ./.env
    volumes:
      - staticfiles:/app/media
      - ./media:/app/media
    ports:
      - 8008:80
    depends_on:
      - web

volumes:
  postgres_data:
  staticfiles: