# Generated by Django 5.0.3 on 2024-03-14 00:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pet', '0002_petimage_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='petimage',
            name='custom_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
