# Generated by Django 5.0.3 on 2024-03-19 20:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pet', '0003_alter_pet_table_alter_petimage_table'),
    ]

    operations = [
        migrations.RenameField(
            model_name='petimage',
            old_name='order',
            new_name='order_number',
        ),
    ]
