# Generated by Django 5.0.3 on 2024-03-26 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pet', '0004_rename_order_petimage_order_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='petimage',
            name='image',
            field=models.ImageField(upload_to='media/pet_images/'),
        ),
    ]
