# Generated by Django 5.0.3 on 2024-03-19 20:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('favorite_pet', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='favoritepet',
            table='favorite_pet',
        ),
    ]
