# Generated by Django 5.0.3 on 2024-03-14 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0002_event_is_confirmed'),
        ('pet', '0003_petimage_custom_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='pets',
            field=models.ManyToManyField(blank=True, related_name='events', to='pet.pet'),
        ),
    ]
