# Generated by Django 5.0.3 on 2024-03-19 20:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0003_alter_event_table_alter_eventimage_table'),
    ]

    operations = [
        migrations.RenameField(
            model_name='eventimage',
            old_name='order',
            new_name='order_number',
        ),
    ]
