# Generated by Django 5.0.3 on 2024-03-14 20:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0003_alter_event_pets'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='pets_ids',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
