# Generated by Django 5.0.3 on 2024-03-21 07:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0004_rename_order_eventimage_order_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='pets_ids',
        ),
    ]
