# Generated by Django 5.0.3 on 2024-03-14 20:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0004_event_pets_ids'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='pets_ids',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
    ]
