# Generated by Django 5.0.3 on 2024-03-21 08:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0006_rename_pets_event_pets_ids'),
    ]

    operations = [
        migrations.RenameField(
            model_name='event',
            old_name='pets_ids',
            new_name='pets',
        ),
    ]
