# Generated by Django 5.0.3 on 2024-03-21 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0007_rename_pets_ids_event_pets'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='pets_ids',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
    ]
