# Generated by Django 5.0.3 on 2024-03-13 00:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cupom', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cupom',
            name='value',
            field=models.CharField(max_length=100),
        ),
    ]
