# Generated by Django 5.0.3 on 2024-03-17 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cupom', '0002_cupom_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cupom',
            name='value',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
