# Generated by Django 5.0.3 on 2024-03-19 20:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cupom', '0003_alter_cupom_value'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='cupom',
            table='cupom',
        ),
    ]
