# Generated by Django 5.0.3 on 2024-03-26 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cupom', '0004_alter_cupom_table'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cupom',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='media/cupom_images/'),
        ),
    ]
