# Generated by Django 5.0.3 on 2024-04-18 08:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cupom', '0005_alter_cupom_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cupom',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='cupom_images/'),
        ),
    ]
