# Generated by Django 5.0.3 on 2024-03-16 00:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('street', models.CharField(max_length=100)),
                ('number', models.CharField(max_length=20)),
                ('district', models.CharField(max_length=100)),
                ('city', models.CharField(max_length=100)),
                ('uf', models.CharField(max_length=2)),
            ],
        ),
    ]
