INSERT INTO address (name, street, number, district, city, uf)
VALUES ('Cobasi Linha Verde', 'Av. Sen. Salgado Filho', 580, 'Prado Velho', 'Curitiba', 'PR'),
       ('Petz Mateus Leme', 'Rua Mateus Leme', 1875, 'Bom Retiro', 'Curitiba', 'PR'),
       ('Hiperzoo Parolin', 'Rua Des. Westphalen', 3488, 'Parolin', 'Curitiba', 'PR'),
       ('Cobasi Maringá', 'Av. João Paulino Vieira Filho', 90, 'Zona 01', 'Maringá', 'PR'),
       ('Mundo Animal Maringá', 'Av. Kakogawa', 718, 'Parque das Grevileas', 'Maringá', 'PR'),
       ('Cobasi Centro', 'Rua Minas Gerais', 88, 'Centro', 'Londrina', 'PR'),
       ('Cobasi Madre Leônia', 'Av. Me. Leônia Milito', 2121, 'Bela Suiça', 'Londrina', 'PR');

INSERT INTO custom_user (type, name, username, email, password, phone, city, uf, pix, site, image, is_superuser, is_staff, is_active)
VALUES (1, 'Ana Maria Rosa', 'anamaria', 'carolzinha_voc@hotmail.com', 'pbkdf2_sha256$720000$KABVdTtVCAEQnUt6hBGqBp$q15nsurxb54JvDFAqc+c5MCynwdfdV4/RvGYbBcQBRg=', '41999999999', 'Curitiba', 'PR', null, null, null, FALSE, FALSE, TRUE),
       (1, 'José Amaro', 'zeze', 'carolzinha_voc@hotmail.com', 'pbkdf2_sha256$720000$FrmLHkrgCnyxtI5WsswvJi$FGEAizBsqf8gnK/wvF5kpCQkiCOhydMIKJq2koVLBMk=', '41999999999', 'Curitiba', 'PR', null, null, null, FALSE, FALSE, TRUE),
       (1, 'Luana Souza', 'luasouza', 'carolzinha_voc@hotmail.com', 'pbkdf2_sha256$720000$31LsQKT0b7Vg0NYqI1lJyH$fyw+SulF3IZNPPYZQPgq6w5NYpSp5AIBh+cK40+CdOU=', '41999999999', 'Curitiba', 'PR', null, null, null, FALSE, FALSE, TRUE),
       (2, 'Protetor Paulo', 'protetorpaulo', 'carolzinha_voc@hotmail.com', 'pbkdf2_sha256$720000$3UkSQzdOwp4E528I0YmqYa$+PqF8O/L5XCug+9ODmZH9sfHF9ZbdiJkmPQmACfvMEw=', '41999999999', 'Curitiba', 'PR', '41999999999', null, 'media/profile_images/paulo.jpg', FALSE, FALSE, TRUE),
       (2, 'Protetora Joana', 'protetorajoana', 'carolzinha_voc@hotmail.com', 'pbkdf2_sha256$720000$7b5M9RYIQEOIqU1ie8Cl2u$wuK3y2p2E+ZDvEa0IxoCu3Xk3WOnAS3YA1yp/jI6woo=', '41999999999', 'Curitiba', 'PR', '41999999999', null, 'media/profile_images/joana.jpg', FALSE, FALSE, TRUE),
       (2, 'ONG Amicao', 'ong_amicao', 'carolzinha_voc@hotmail.com', 'pbkdf2_sha256$720000$sD5diFVpWTxQTTtsVCRpPE$EMpZAthaOMdBgGkcewBiYE+fdkGva8oqpRIlOTIRYGM=', '41999999999', 'Curitiba', 'PR', '41999999999', null, 'media/profile_images/amicao.jpg', FALSE, FALSE, TRUE),
       (3, 'Carla Cobasi', 'cobasi', 'carolzinha_voc@hotmail.com', 'pbkdf2_sha256$720000$YjJM8mTnsPiVKE2mLsjK7f$7ZlBK1XPCSEJ/QRTAohcneULgcOWevTyrnTyl8/NZ04=', '41999999999', 'Curitiba', 'PR', '41999999999', 'http://www.cobasi.com.br', 'media/profile_images/cobasi.jpg', FALSE, FALSE, TRUE),
       (3, 'João Petz', 'petz', 'carolzinha_voc@hotmail.com', 'pbkdf2_sha256$720000$5VX6dU48fBG0lkgIQGqkRt$o+6xeHCQ9TVjR5bydC/mO95ZuD6mjEyWbGhuoYPxoZ8=', '41999999999', 'Curitiba', 'PR', '41999999999', 'http://www.petz.com.br', 'media/profile_images/petz.jpg', FALSE, FALSE, TRUE),
       (3, 'Jéssica Zee', 'zeedog', 'carolzinha_voc@hotmail.com', 'pbkdf2_sha256$720000$qMaLMfLURvnCMzaDwvADD3$dSuiKOYXxd/B51QmP93XGFKcBCw71kxilANmgno8Loo=', '41999999999', 'Curitiba', 'PR', '41999999999', 'http://www.zeedog.com.br', 'media/profile_images/zee.jpg', FALSE, FALSE, TRUE);

INSERT INTO cupom (value, description, expiration, owner_id, is_active, image)
VALUES ('SUPERSALE', 'Aproveite a supersale do ano!\nDescontos de até 50%', '2024-03-10', (SELECT COALESCE((SELECT id FROM custom_user WHERE name='Carla Cobasi'), 0)), TRUE, 'media/cupom_images/cupom1.jpg'),
       ('PRIMEIRACOMPRA', '15% de desconto para a sua primeira compra.', '2024-03-20', (SELECT COALESCE((SELECT id FROM custom_user WHERE name='Carla Cobasi'), 0)), TRUE, 'media/cupom_images/cupom2.jpg'),
       ('FRETEGRATIS', 'Frete grátis para compras acima de R$99', '2024-03-21', (SELECT COALESCE((SELECT id FROM custom_user WHERE name='Carla Cobasi'), 0)), TRUE, 'media/cupom_images/cupom3.jpg'),
       ('BANHO15', 'Pacotes de banhos com 15% de desconto.\nMarque um horário', '2024-03-22', (SELECT COALESCE((SELECT id FROM custom_user WHERE name='Carla Cobasi'), 0) + 1), TRUE, 'media/cupom_images/cupom4.jpg'),
       ('COLEIRA10', 'Coleiras selecionadas com 10% de desconto', '2024-03-23', (SELECT COALESCE((SELECT id FROM custom_user WHERE name='Carla Cobasi'), 0) + 1), TRUE, 'media/cupom_images/cupom5.jpg'),
       ('SALDAO', 'Venha conferir o saldão de camas', '2024-03-23', (SELECT COALESCE((SELECT id FROM custom_user WHERE name='Carla Cobasi'), 0) + 1), TRUE, 'media/cupom_images/cupom6.jpg'),
       ('ANIVERSARIO', 'No aniversário da Petz, você ganha 10% de desconto', '2024-03-23', (SELECT COALESCE((SELECT id FROM custom_user WHERE name='Carla Cobasi'), 0) + 1), TRUE, 'media/cupom_images/cupom7.jpg'),
       ('15OFF', 'Produtos selecionados com 15% de desconto', '2024-03-23', (SELECT COALESCE((SELECT id FROM custom_user WHERE name='Carla Cobasi'), 0) + 1), TRUE, 'media/cupom_images/cupom8.jpg'),
       ('TOSAGRATIS', 'Adquira o kit banho e ganhe tosa grátis', '2024-03-23', (SELECT COALESCE((SELECT id FROM custom_user WHERE name='Carla Cobasi'), 0) + 1), TRUE, 'media/cupom_images/cupom9.jpg'),
       ('FRETESUL', 'Frete grátis para toda a região Sul', '2024-03-24', (SELECT COALESCE((SELECT id FROM custom_user WHERE name='Carla Cobasi'), 0) + 2), TRUE, 'media/cupom_images/cupom10.jpg'),
       ('10OFF', '10% de desconto em produtos selecionados', '2024-04-02', (SELECT COALESCE((SELECT id FROM custom_user WHERE name='Carla Cobasi'), 0) + 2), TRUE, 'media/cupom_images/cupom11.jpg'),
       ('PASCOAPET', 'Doces para os pets com 20% de desconto', '2024-04-02', (SELECT COALESCE((SELECT id FROM custom_user WHERE name='Carla Cobasi'), 0) + 2), TRUE, 'media/cupom_images/cupom12.jpg'),
       ('PASCOAPET', 'Doces para os pets com 20% de desconto', '2024-04-02', (SELECT COALESCE((SELECT id FROM custom_user WHERE name='Carla Cobasi'), 0) + 2), TRUE, 'media/cupom_images/cupom13.jpg'),
       ('PASCOAPET', 'Doces para os pets com 20% de desconto', '2024-04-02', (SELECT COALESCE((SELECT id FROM custom_user WHERE name='Carla Cobasi'), 0) + 2), TRUE, 'media/cupom_images/cupom14.jpg'),
       ('PASCOAPET', 'Doces para os pets com 20% de desconto', '2024-04-02', (SELECT COALESCE((SELECT id FROM custom_user WHERE name='Carla Cobasi'), 0) + 2), TRUE, 'media/cupom_images/cupom15.jpg');

INSERT INTO pet (name, type, gender, age_year, age_month, weight, size, breed, owner_id, personality, get_along, description, is_active, followers)
VALUES ('Lua', 1, 'F', 0, 6, 4.5, 'miniatura', 1, (SELECT COALESCE((SELECT id FROM custom_user WHERE name='Protetor Paulo'), 0)), '{1,3,4}', '{1,2,3}', 'Lua é linda.\nÓtima companheira.', TRUE, 3),
       ('Brisa', 1, 'F', 0, 1, 25, 'grande', 1, (SELECT COALESCE((SELECT id FROM custom_user WHERE name='Protetor Paulo'), 0)), '{8,10}', '{1}', 'Adora passear.\nAma outos animais.', TRUE, 3),
       ('Mona', 1, 'F', 7, 6, 4.5, 'miniatura', 1, (SELECT COALESCE((SELECT id FROM custom_user WHERE name='Protetor Paulo'), 0)), '{1,3,4}', '{3}', 'Quer colo o tempo todo.\nCompanhia ideal.', TRUE, 3),
       ('Furacao', 1, 'M', 2, 6, 4.5, 'médio', 2, (SELECT COALESCE((SELECT id FROM custom_user WHERE name='Protetor Paulo'), 0)), '{2,5,7}', '{1,2,3}', 'Brincalhão e alegre.', TRUE, 2),
       ('Gohan', 1, 'M', 1, 0, 4, 'miniatura', 34, (SELECT COALESCE((SELECT id FROM custom_user WHERE name='Protetor Paulo'), 0)), '{1,6,7}', '{1,2,3}', '100% fofura', TRUE, 2),
       ('Liu', 1, 'M', 9, 5, 12, 'médio', 4, (SELECT COALESCE((SELECT id FROM custom_user WHERE name='Protetor Paulo'), 0)), '{1,6,7}', '{1,3}', 'Quer colo o tempo todo.\nCompanhia ideal.', TRUE, 2),
       ('Fiona', 1, 'F', 0, 10, 15, 'médio', 1, (SELECT COALESCE((SELECT id FROM custom_user WHERE name='Protetor Paulo'), 0)), '{1,3,4}', '{1,2,3}', 'Quer colo o tempo todo.\nCompanhia ideal.', TRUE, 2),
       ('Mimi', 2, 'F', 0, 11, 6, 'pequeno', 1, (SELECT COALESCE((SELECT id FROM custom_user WHERE name='Protetor Paulo'), 0)), '{1,3,4}', '{1,2,3}', 'Quer colo o tempo todo.\nCompanhia ideal.', TRUE, 0),
       ('King', 2, 'M', 2, 0, 10, 'pequeno', 1, (SELECT COALESCE((SELECT id FROM custom_user WHERE name='Protetor Paulo'), 0)), '{1,3,4}', '{1,2,3}', 'Quer colo o tempo todo.\nCompanhia ideal.', TRUE, 0),
       ('Caju', 1, 'M', 0, 6, 4.5, 'miniatura', 1, (SELECT COALESCE((SELECT id FROM custom_user WHERE name='Protetor Paulo'), 0)), '{1,3,4}', '{1,2,3}', 'Quer colo o tempo todo.\nCompanhia ideal.', TRUE, 0),
       ('Cacau', 1, 'F', 2, 0, 5, 'miniatura', 1,  (SELECT COALESCE((SELECT id FROM custom_user WHERE name='Protetor Paulo'), 0) + 1), '{1,3,4}', '{1,2,3}', 'Quer colo o tempo todo.\nCompanhia ideal.', TRUE, 0),
       ('Linda', 1, 'F', 2, 0, 5, 'miniatura', 1,  (SELECT COALESCE((SELECT id FROM custom_user WHERE name='Protetor Paulo'), 0) + 1), '{1,3,4}', '{1,2,3}', 'Quer colo o tempo todo.\nCompanhia ideal.', TRUE, 0),
       ('Jana', 1, 'F', 2, 0, 5, 'miniatura', 1,  (SELECT COALESCE((SELECT id FROM custom_user WHERE name='Protetor Paulo'), 0) + 1), '{1,3,4}', '{1,2,3}', 'Quer colo o tempo todo.\nCompanhia ideal.', TRUE, 0),
       ('Mel', 1, 'F', 2, 0, 5, 'miniatura', 1,  (SELECT COALESCE((SELECT id FROM custom_user WHERE name='Protetor Paulo'), 0) + 1), '{1,3,4}', '{1,2,3}', 'Quer colo o tempo todo.\nCompanhia ideal.', TRUE, 0),
       ('Box', 1, 'M', 2, 0, 12, 'médio', 1,  (SELECT COALESCE((SELECT id FROM custom_user WHERE name='Protetor Paulo'), 0) + 1), '{1,3,4}', '{1,2,3}', 'Quer colo o tempo todo.\nCompanhia ideal.', TRUE, 0),
       ('Pingado', 1, 'M', 2, 0, 12, 'médio', 1,  (SELECT COALESCE((SELECT id FROM custom_user WHERE name='Protetor Paulo'), 0) + 1), '{1,3,4}', '{1,2,3}', 'Quer colo o tempo todo.\nCompanhia ideal.', TRUE, 0),
       ('Bono', 1, 'M', 2, 0, 12, 'médio', 1,  (SELECT COALESCE((SELECT id FROM custom_user WHERE name='Protetor Paulo'), 0) + 1), '{6,7,9}', '{1,2,3}', 'Quer colo o tempo todo.\nCompanhia ideal.', TRUE, 0),
       ('Frufru', 1, 'F', 2, 0, 12, 'médio', 1,  (SELECT COALESCE((SELECT id FROM custom_user WHERE name='Protetor Paulo'), 0) + 1), '{6,7,9}', '{1,2,3}', 'Quer colo o tempo todo.\nCompanhia ideal.', TRUE, 0),
       ('Branca', 1, 'F', 2, 0, 12, 'médio', 1,  (SELECT COALESCE((SELECT id FROM custom_user WHERE name='Protetor Paulo'), 0) + 1), '{6,7,9}', '{1,2,3}', 'Quer colo o tempo todo.\nCompanhia ideal.', TRUE, 0),
       ('Capitu', 1, 'F', 2, 0, 20, 'grande', 1,  (SELECT COALESCE((SELECT id FROM custom_user WHERE name='Protetor Paulo'), 0) + 1), '{6,7,9}', '{1,2,3}', 'Quer colo o tempo todo.\nCompanhia ideal.', TRUE, 0),
       ('Paçoca', 1, 'F', 2, 0, 20, 'grande', 1,  (SELECT COALESCE((SELECT id FROM custom_user WHERE name='Protetor Paulo'), 0) + 1), '{6,7,9}', '{1,2,3}', 'Quer colo o tempo todo.\nCompanhia ideal.', TRUE, 0),
       ('Mia', 2, 'F', 2, 0, 6, 'miniatura', 1,  (SELECT COALESCE((SELECT id FROM custom_user WHERE name='Protetor Paulo'), 0) + 1), '{6,7,9}', '{1,2,3}', 'Quer colo o tempo todo.\nCompanhia ideal.', TRUE, 0),
       ('Liu', 1, 'M', 9, 5, 12, 'médio', 4,  (SELECT COALESCE((SELECT id FROM custom_user WHERE name='Protetor Paulo'), 0) + 2), '{1,6,7}', '{1,3}', 'Quer colo o tempo todo.\nCompanhia ideal.', TRUE, 0),
       ('Fiona', 1, 'F', 0, 10, 15, 'médio', 1, (SELECT COALESCE((SELECT id FROM custom_user WHERE name='Protetor Paulo'), 0) + 2), '{1,3,4}', '{1,2,3}', 'Quer colo o tempo todo.\nCompanhia ideal.', TRUE, 0),
       ('Mimi', 2, 'F', 0, 11, 6, 'pequeno', 1, (SELECT COALESCE((SELECT id FROM custom_user WHERE name='Protetor Paulo'), 0) + 2), '{1,3,4}', '{1,2,3}', 'Quer colo o tempo todo.\nCompanhia ideal.', TRUE, 0),
       ('King', 2, 'M', 2, 0, 10, 'pequeno', 1, (SELECT COALESCE((SELECT id FROM custom_user WHERE name='Protetor Paulo'), 0) + 2), '{1,3,4}', '{1,2,3}', 'Quer colo o tempo todo.\nCompanhia ideal.', TRUE, 0),
       ('Caju', 1, 'M', 0, 6, 4.5, 'miniatura', 1, (SELECT COALESCE((SELECT id FROM custom_user WHERE name='Protetor Paulo'), 0) + 2), '{1,3,4}', '{1,2,3}', 'Quer colo o tempo todo.\nCompanhia ideal.', TRUE, 0),
       ('Cacau', 1, 'F', 2, 0, 5, 'miniatura', 1, (SELECT COALESCE((SELECT id FROM custom_user WHERE name='Protetor Paulo'), 0) + 2), '{1,3,4}', '{1,2,3}', 'Quer colo o tempo todo.\nCompanhia ideal.', TRUE, 0),
       ('Linda', 1, 'F', 2, 0, 5, 'miniatura', 1, (SELECT COALESCE((SELECT id FROM custom_user WHERE name='Protetor Paulo'), 0) + 2), '{1,3,4}', '{1,2,3}', 'Quer colo o tempo todo.\nCompanhia ideal.', TRUE, 0),
       ('Jana', 1, 'F', 2, 0, 5, 'miniatura', 1, (SELECT COALESCE((SELECT id FROM custom_user WHERE name='Protetor Paulo'), 0) + 2), '{1,3,4}', '{1,2,3}', 'Quer colo o tempo todo.\nCompanhia ideal.', TRUE, 0),
       ('Mel', 1, 'F', 2, 0, 5, 'miniatura', 1, (SELECT COALESCE((SELECT id FROM custom_user WHERE name='Protetor Paulo'), 0) + 2), '{1,3,4}', '{1,2,3}', 'Quer colo o tempo todo.\nCompanhia ideal.', TRUE, 0),
       ('Box', 1, 'M', 2, 0, 12, 'médio', 1, (SELECT COALESCE((SELECT id FROM custom_user WHERE name='Protetor Paulo'), 0) + 2), '{1,3,4}', '{1,2,3}', 'Quer colo o tempo todo.\nCompanhia ideal.', TRUE, 0),
       ('Pingado', 1, 'M', 2, 0, 12, 'médio', 1, (SELECT COALESCE((SELECT id FROM custom_user WHERE name='Protetor Paulo'), 0) + 2), '{1,3,4}', '{1,2,3}', 'Quer colo o tempo todo.\nCompanhia ideal.', TRUE, 0),
       ('Bono', 1, 'M', 2, 0, 12, 'médio', 1, (SELECT COALESCE((SELECT id FROM custom_user WHERE name='Protetor Paulo'), 0) + 2), '{6,7,9}', '{1,2,3}', 'Quer colo o tempo todo.\nCompanhia ideal.', TRUE, 0),
       ('Frufru', 1, 'F', 2, 0, 12, 'médio', 1, (SELECT COALESCE((SELECT id FROM custom_user WHERE name='Protetor Paulo'), 0) + 2), '{6,7,9}', '{1,2,3}', 'Quer colo o tempo todo.\nCompanhia ideal.', TRUE, 0),
       ('Branca', 1, 'F', 2, 0, 12, 'médio', 1, (SELECT COALESCE((SELECT id FROM custom_user WHERE name='Protetor Paulo'), 0) + 2), '{6,7,9}', '{1,2,3}', 'Quer colo o tempo todo.\nCompanhia ideal.', TRUE, 0),
       ('Capitu', 1, 'F', 2, 0, 20, 'grande', 1, (SELECT COALESCE((SELECT id FROM custom_user WHERE name='Protetor Paulo'), 0) + 2), '{6,7,9}', '{1,2,3}', 'Quer colo o tempo todo.\nCompanhia ideal.', TRUE, 0),
       ('Paçoca', 1, 'F', 2, 0, 20, 'grande', 1, (SELECT COALESCE((SELECT id FROM custom_user WHERE name='Protetor Paulo'), 0) + 2), '{6,7,9}', '{1,2,3}', 'Quer colo o tempo todo.\nCompanhia ideal.', TRUE, 0),
       ('Mia', 2, 'F', 2, 0, 6, 'miniatura', 1, (SELECT COALESCE((SELECT id FROM custom_user WHERE name='Protetor Paulo'), 0) + 2), '{6,7,9}', '{1,2,3}', 'Quer colo o tempo todo.\nCompanhia ideal.', TRUE, 0);

INSERT INTO pet_image (pet_id, image, order_number)
VALUES ((SELECT COALESCE((SELECT id FROM pet WHERE name='Lua'), 0)), 'media/pet_images/lua.jpg', 0),
       ((SELECT COALESCE((SELECT id FROM pet WHERE name='Lua'), 0)), 'media/pet_images/lua1.jpg', 1),
       ((SELECT COALESCE((SELECT id FROM pet WHERE name='Lua'), 0)), 'media/pet_images/lua2.jpg', 2),
       ((SELECT COALESCE((SELECT id FROM pet WHERE name='Lua'), 0) + 1), 'media/pet_images/brisa1.jpg', 1),
       ((SELECT COALESCE((SELECT id FROM pet WHERE name='Lua'), 0) + 1), 'media/pet_images/brisa2.jpg', 2),
       ((SELECT COALESCE((SELECT id FROM pet WHERE name='Lua'), 0) + 1), 'media/pet_images/brisa.jpg', 0),
       ((SELECT COALESCE((SELECT id FROM pet WHERE name='Lua'), 0) + 2), 'media/pet_images/mona.jpg', 0),
       ((SELECT COALESCE((SELECT id FROM pet WHERE name='Lua'), 0) + 2), 'media/pet_images/mona1.jpg', 1),
       ((SELECT COALESCE((SELECT id FROM pet WHERE name='Lua'), 0) + 2), 'media/pet_images/mona3.jpg', 2),
       ((SELECT COALESCE((SELECT id FROM pet WHERE name='Lua'), 0) + 2), 'media/pet_images/mona2.jpg', 3),
       ((SELECT COALESCE((SELECT id FROM pet WHERE name='Lua'), 0) + 3), 'media/pet_images/furacao.jpg', 0),
       ((SELECT COALESCE((SELECT id FROM pet WHERE name='Lua'), 0) + 3), 'media/pet_images/furacao1.jpg', 1),
       ((SELECT COALESCE((SELECT id FROM pet WHERE name='Lua'), 0) + 4), 'media/pet_images/gohan.jpg', 0),
       ((SELECT COALESCE((SELECT id FROM pet WHERE name='Lua'), 0) + 4), 'media/pet_images/gohan1.jpg', 1),
       ((SELECT COALESCE((SELECT id FROM pet WHERE name='Lua'), 0) + 4), 'media/pet_images/gohan2.jpg', 2),
       ((SELECT COALESCE((SELECT id FROM pet WHERE name='Lua'), 0) + 5), 'media/pet_images/liu.jpg', 0),
       ((SELECT COALESCE((SELECT id FROM pet WHERE name='Lua'), 0) + 5), 'media/pet_images/liu1.jpg', 1),
       ((SELECT COALESCE((SELECT id FROM pet WHERE name='Lua'), 0) + 6), 'media/pet_images/fiona.jpg', 0),
       ((SELECT COALESCE((SELECT id FROM pet WHERE name='Lua'), 0) + 7), 'media/pet_images/mimi.jpg', 0),
       ((SELECT COALESCE((SELECT id FROM pet WHERE name='Lua'), 0) + 8), 'media/pet_images/king.jpg', 0),
       ((SELECT COALESCE((SELECT id FROM pet WHERE name='Lua'), 0) + 8), 'media/pet_images/king1.jpg', 1),
       ((SELECT COALESCE((SELECT id FROM pet WHERE name='Lua'), 0) + 9), 'media/pet_images/caju.jpg', 0),
       ((SELECT COALESCE((SELECT id FROM pet WHERE name='Lua'), 0) + 10), 'media/pet_images/cacau.jpg', 0),
       ((SELECT COALESCE((SELECT id FROM pet WHERE name='Lua'), 0) + 11), 'media/pet_images/linda.jpg', 0),
       ((SELECT COALESCE((SELECT id FROM pet WHERE name='Lua'), 0) + 12), 'media/pet_images/jana.jpg', 0),
       ((SELECT COALESCE((SELECT id FROM pet WHERE name='Lua'), 0) + 13), 'media/pet_images/mel.jpg', 0),
       ((SELECT COALESCE((SELECT id FROM pet WHERE name='Lua'), 0) + 14), 'media/pet_images/box.jpg', 0),
       ((SELECT COALESCE((SELECT id FROM pet WHERE name='Lua'), 0) + 15), 'media/pet_images/pingado.jpg', 0),
       ((SELECT COALESCE((SELECT id FROM pet WHERE name='Lua'), 0) + 16), 'media/pet_images/bono.jpg', 0),
       ((SELECT COALESCE((SELECT id FROM pet WHERE name='Lua'), 0) + 17), 'media/pet_images/frufru.jpg', 0),
       ((SELECT COALESCE((SELECT id FROM pet WHERE name='Lua'), 0) + 18), 'media/pet_images/branca.jpg', 0),
       ((SELECT COALESCE((SELECT id FROM pet WHERE name='Lua'), 0) + 19), 'media/pet_images/capitu.jpg', 0),
       ((SELECT COALESCE((SELECT id FROM pet WHERE name='Lua'), 0) + 20), 'media/pet_images/mia.jpg', 0),
       ((SELECT COALESCE((SELECT id FROM pet WHERE name='Lua'), 0) + 20), 'media/pet_images/mia1.jpg', 1),
       ((SELECT COALESCE((SELECT id FROM pet WHERE name='Lua'), 0) + 21), 'media/pet_images/liu2.jpg', 0),
       ((SELECT COALESCE((SELECT id FROM pet WHERE name='Lua'), 0) + 21), 'media/pet_images/liu3.jpg', 1),
       ((SELECT COALESCE((SELECT id FROM pet WHERE name='Lua'), 0) + 22), 'media/pet_images/fiona1.jpg', 0),
       ((SELECT COALESCE((SELECT id FROM pet WHERE name='Lua'), 0) + 23), 'media/pet_images/mimi1.jpg', 0),
       ((SELECT COALESCE((SELECT id FROM pet WHERE name='Lua'), 0) + 24), 'media/pet_images/king2.jpg', 0),
       ((SELECT COALESCE((SELECT id FROM pet WHERE name='Lua'), 0) + 24), 'media/pet_images/king3.jpg', 1),
       ((SELECT COALESCE((SELECT id FROM pet WHERE name='Lua'), 0) + 25), 'media/pet_images/caju1.jpg', 0),
       ((SELECT COALESCE((SELECT id FROM pet WHERE name='Lua'), 0) + 26), 'media/pet_images/cacau1.jpg', 0),
       ((SELECT COALESCE((SELECT id FROM pet WHERE name='Lua'), 0) + 27), 'media/pet_images/linda1.jpg', 0),
       ((SELECT COALESCE((SELECT id FROM pet WHERE name='Lua'), 0) + 28), 'media/pet_images/jana1.jpg', 0),
       ((SELECT COALESCE((SELECT id FROM pet WHERE name='Lua'), 0) + 29), 'media/pet_images/mel1.jpg', 0),
       ((SELECT COALESCE((SELECT id FROM pet WHERE name='Lua'), 0) + 30), 'media/pet_images/box1.jpg', 0),
       ((SELECT COALESCE((SELECT id FROM pet WHERE name='Lua'), 0) + 31), 'media/pet_images/pingado1.jpg', 0),
       ((SELECT COALESCE((SELECT id FROM pet WHERE name='Lua'), 0) + 32), 'media/pet_images/bono1.jpg', 0),
       ((SELECT COALESCE((SELECT id FROM pet WHERE name='Lua'), 0) + 33), 'media/pet_images/frufru1.jpg', 0),
       ((SELECT COALESCE((SELECT id FROM pet WHERE name='Lua'), 0) + 34), 'media/pet_images/branca1.jpg', 0),
       ((SELECT COALESCE((SELECT id FROM pet WHERE name='Lua'), 0) + 35), 'media/pet_images/capitu1.jpg', 0),
       ((SELECT COALESCE((SELECT id FROM pet WHERE name='Lua'), 0) + 36), 'media/pet_images/mia2.jpg', 0),
       ((SELECT COALESCE((SELECT id FROM pet WHERE name='Lua'), 0) + 36), 'media/pet_images/mia3.jpg', 1);

INSERT INTO event (date_hour_initial, date_hour_end, address_id, owner_id, description, is_active, is_confirmed, followers, pets_ids)
VALUES ('2024-03-23 09:00:00', '2024-03-23 17:00:00', 1, (SELECT COALESCE((SELECT id FROM custom_user WHERE name='Protetor Paulo'), 0)), 'Feira anual de adoção', TRUE, FALSE, 3, ''),
       ('2024-03-24 09:00:00', '2024-03-24 17:00:00', 1, (SELECT COALESCE((SELECT id FROM custom_user WHERE name='Protetor Paulo'), 0)), 'Adoção de animais e palestra de socialização para cachorros', TRUE, FALSE, 3, ''),
       ('2024-03-30 09:00:00', '2024-03-30 17:00:00', 1, (SELECT COALESCE((SELECT id FROM custom_user WHERE name='Protetor Paulo'), 0)), 'Adoção de animais e palestra de socialização para cachorros', TRUE, FALSE, 3, ''),
       ('2024-03-31 09:00:00', '2024-03-31 17:00:00', 1, (SELECT COALESCE((SELECT id FROM custom_user WHERE name='Protetor Paulo'), 0)), 'Adoção de animais e palestra de socialização para cachorros', TRUE, FALSE, 2, ''),
       ('2024-04-06 09:00:00', '2024-04-06 17:00:00', 1, (SELECT COALESCE((SELECT id FROM custom_user WHERE name='Protetor Paulo'), 0)), 'Adoção de animais e palestra de socialização para cachorros', TRUE, FALSE, 2, ''),
       ('2024-04-07 09:00:00', '2024-04-07 17:00:00', 1, (SELECT COALESCE((SELECT id FROM custom_user WHERE name='Protetor Paulo'), 0)), 'Adoção de animais e palestra de socialização para cachorros', TRUE, FALSE, 2, ''),
       ('2024-04-13 09:00:00', '2024-04-13 17:00:00', 1, (SELECT COALESCE((SELECT id FROM custom_user WHERE name='Protetor Paulo'), 0)), 'Adoção de animais e palestra de socialização para cachorros', TRUE, FALSE, 2, ''),
       ('2024-04-14 09:00:00', '2024-04-14 17:00:00', 1, (SELECT COALESCE((SELECT id FROM custom_user WHERE name='Protetor Paulo'), 0)), 'Adoção de animais e palestra de socialização para cachorros', TRUE, FALSE, 0, ''),
       ('2024-03-23 09:00:00', '2024-03-23 17:00:00', 4, (SELECT COALESCE((SELECT id FROM custom_user WHERE name='Protetor Paulo'), 0) + 1), 'Adoção de animais e palestra de socialização para cachorros', TRUE, FALSE, 0, ''),
       ('2024-03-24 09:00:00', '2024-03-24 17:00:00', 4, (SELECT COALESCE((SELECT id FROM custom_user WHERE name='Protetor Paulo'), 0) + 1), 'Adoção de animais e palestra de socialização para cachorros', TRUE, FALSE, 0, ''),
       ('2024-03-30 09:00:00', '2024-03-30 17:00:00', 4, (SELECT COALESCE((SELECT id FROM custom_user WHERE name='Protetor Paulo'), 0) + 1), 'Adoção de animais e palestra de socialização para cachorros', TRUE, FALSE, 0, ''),
       ('2024-03-31 09:00:00', '2024-03-31 17:00:00', 4, (SELECT COALESCE((SELECT id FROM custom_user WHERE name='Protetor Paulo'), 0) + 1), 'Adoção de animais e palestra de socialização para cachorros', TRUE, FALSE, 0, ''),
       ('2024-04-06 09:00:00', '2024-04-06 17:00:00', 4, (SELECT COALESCE((SELECT id FROM custom_user WHERE name='Protetor Paulo'), 0) + 1), 'Adoção de animais e palestra de socialização para cachorros', TRUE, FALSE, 0, ''),
       ('2024-04-07 09:00:00', '2024-04-07 17:00:00', 4, (SELECT COALESCE((SELECT id FROM custom_user WHERE name='Protetor Paulo'), 0) + 1), 'Adoção de animais e palestra de socialização para cachorros', TRUE, FALSE, 0, ''),
       ('2024-04-13 09:00:00', '2024-04-13 17:00:00', 4, (SELECT COALESCE((SELECT id FROM custom_user WHERE name='Protetor Paulo'), 0) + 1), 'Adoção de animais e palestra de socialização para cachorros', TRUE, FALSE, 0, ''),
       ('2024-04-14 09:00:00', '2024-04-14 17:00:00', 5, (SELECT COALESCE((SELECT id FROM custom_user WHERE name='Protetor Paulo'), 0) + 1), 'Adoção de animais e palestra de socialização para cachorros', TRUE, FALSE, 0, ''),
       ('2024-03-23 09:00:00', '2024-03-23 17:00:00', 6, (SELECT COALESCE((SELECT id FROM custom_user WHERE name='Protetor Paulo'), 0) + 2), 'Adoção de animais e palestra de socialização para cachorros', TRUE, FALSE, 0, ''),
       ('2024-03-24 09:00:00', '2024-03-24 17:00:00', 6, (SELECT COALESCE((SELECT id FROM custom_user WHERE name='Protetor Paulo'), 0) + 2), 'Adoção de animais e palestra de socialização para cachorros', TRUE, FALSE, 0, ''),
       ('2024-03-30 09:00:00', '2024-03-30 17:00:00', 6, (SELECT COALESCE((SELECT id FROM custom_user WHERE name='Protetor Paulo'), 0) + 2), 'Adoção de animais e palestra de socialização para cachorros', TRUE, FALSE, 0, ''),
       ('2024-03-31 09:00:00', '2024-03-31 17:00:00', 6, (SELECT COALESCE((SELECT id FROM custom_user WHERE name='Protetor Paulo'), 0) + 2), 'Adoção de animais e palestra de socialização para cachorros', TRUE, FALSE, 0, ''),
       ('2024-04-06 09:00:00', '2024-04-06 17:00:00', 6, (SELECT COALESCE((SELECT id FROM custom_user WHERE name='Protetor Paulo'), 0) + 2), 'Adoção de animais e palestra de socialização para cachorros', TRUE, FALSE, 0, ''),
       ('2024-04-07 09:00:00', '2024-04-07 17:00:00', 6, (SELECT COALESCE((SELECT id FROM custom_user WHERE name='Protetor Paulo'), 0) + 2), 'Adoção de animais e palestra de socialização para cachorros', TRUE, FALSE, 0, ''),
       ('2024-04-13 09:00:00', '2024-04-13 17:00:00', 6, (SELECT COALESCE((SELECT id FROM custom_user WHERE name='Protetor Paulo'), 0) + 2), 'Adoção de animais e palestra de socialização para cachorros', TRUE, FALSE, 0, ''),
       ('2024-04-14 09:00:00', '2024-04-14 17:00:00', 6, (SELECT COALESCE((SELECT id FROM custom_user WHERE name='Protetor Paulo'), 0) + 2), 'Adoção de animais e palestra de socialização para cachorros', TRUE, FALSE, 0, '');

INSERT INTO event_pets (event_id, pet_id)
VALUES 	((SELECT COALESCE((SELECT id FROM event WHERE description='Feira anual de adoção'), 0)), (SELECT COALESCE((SELECT id FROM pet WHERE name='Lua'), 0))),
        ((SELECT COALESCE((SELECT id FROM event WHERE description='Feira anual de adoção'), 0)), (SELECT COALESCE((SELECT id FROM pet WHERE name='Lua'), 0)) + 1),
        ((SELECT COALESCE((SELECT id FROM event WHERE description='Feira anual de adoção'), 0)), (SELECT COALESCE((SELECT id FROM pet WHERE name='Lua'), 0)) + 2),
        ((SELECT COALESCE((SELECT id FROM event WHERE description='Feira anual de adoção'), 0) + 1), (SELECT COALESCE((SELECT id FROM pet WHERE name='Lua'), 0)) + 3),
        ((SELECT COALESCE((SELECT id FROM event WHERE description='Feira anual de adoção'), 0) + 1), (SELECT COALESCE((SELECT id FROM pet WHERE name='Lua'), 0)) + 4),
        ((SELECT COALESCE((SELECT id FROM event WHERE description='Feira anual de adoção'), 0) + 1), (SELECT COALESCE((SELECT id FROM pet WHERE name='Lua'), 0)) + 5),
        ((SELECT COALESCE((SELECT id FROM event WHERE description='Feira anual de adoção'), 0) + 2), (SELECT COALESCE((SELECT id FROM pet WHERE name='Lua'), 0)) + 6),
        ((SELECT COALESCE((SELECT id FROM event WHERE description='Feira anual de adoção'), 0) + 2), (SELECT COALESCE((SELECT id FROM pet WHERE name='Lua'), 0)) + 7),
        ((SELECT COALESCE((SELECT id FROM event WHERE description='Feira anual de adoção'), 0) + 2), (SELECT COALESCE((SELECT id FROM pet WHERE name='Lua'), 0)) + 8),
        ((SELECT COALESCE((SELECT id FROM event WHERE description='Feira anual de adoção'), 0) + 3), (SELECT COALESCE((SELECT id FROM pet WHERE name='Lua'), 0)) + 9),
        ((SELECT COALESCE((SELECT id FROM event WHERE description='Feira anual de adoção'), 0) + 3), (SELECT COALESCE((SELECT id FROM pet WHERE name='Lua'), 0)) + 10),
        ((SELECT COALESCE((SELECT id FROM event WHERE description='Feira anual de adoção'), 0) + 3), (SELECT COALESCE((SELECT id FROM pet WHERE name='Lua'), 0)) + 11),
        ((SELECT COALESCE((SELECT id FROM event WHERE description='Feira anual de adoção'), 0) + 4), (SELECT COALESCE((SELECT id FROM pet WHERE name='Lua'), 0)) + 12),
        ((SELECT COALESCE((SELECT id FROM event WHERE description='Feira anual de adoção'), 0) + 4), (SELECT COALESCE((SELECT id FROM pet WHERE name='Lua'), 0)) + 13),
        ((SELECT COALESCE((SELECT id FROM event WHERE description='Feira anual de adoção'), 0) + 4), (SELECT COALESCE((SELECT id FROM pet WHERE name='Lua'), 0)) + 14),
        ((SELECT COALESCE((SELECT id FROM event WHERE description='Feira anual de adoção'), 0) + 5), (SELECT COALESCE((SELECT id FROM pet WHERE name='Lua'), 0)) + 15),
        ((SELECT COALESCE((SELECT id FROM event WHERE description='Feira anual de adoção'), 0) + 5), (SELECT COALESCE((SELECT id FROM pet WHERE name='Lua'), 0)) + 16),
        ((SELECT COALESCE((SELECT id FROM event WHERE description='Feira anual de adoção'), 0) + 5), (SELECT COALESCE((SELECT id FROM pet WHERE name='Lua'), 0)) + 17),
        ((SELECT COALESCE((SELECT id FROM event WHERE description='Feira anual de adoção'), 0) + 6), (SELECT COALESCE((SELECT id FROM pet WHERE name='Lua'), 0)) + 18),
        ((SELECT COALESCE((SELECT id FROM event WHERE description='Feira anual de adoção'), 0) + 6), (SELECT COALESCE((SELECT id FROM pet WHERE name='Lua'), 0)) + 19),
        ((SELECT COALESCE((SELECT id FROM event WHERE description='Feira anual de adoção'), 0) + 6), (SELECT COALESCE((SELECT id FROM pet WHERE name='Lua'), 0)) + 20),
        ((SELECT COALESCE((SELECT id FROM event WHERE description='Feira anual de adoção'), 0) + 7), (SELECT COALESCE((SELECT id FROM pet WHERE name='Lua'), 0)) + 3),
        ((SELECT COALESCE((SELECT id FROM event WHERE description='Feira anual de adoção'), 0) + 7), (SELECT COALESCE((SELECT id FROM pet WHERE name='Lua'), 0)) + 4),
        ((SELECT COALESCE((SELECT id FROM event WHERE description='Feira anual de adoção'), 0) + 7), (SELECT COALESCE((SELECT id FROM pet WHERE name='Lua'), 0)) + 5),
        ((SELECT COALESCE((SELECT id FROM event WHERE description='Feira anual de adoção'), 0) + 8), (SELECT COALESCE((SELECT id FROM pet WHERE name='Lua'), 0)) + 6),
        ((SELECT COALESCE((SELECT id FROM event WHERE description='Feira anual de adoção'), 0) + 8), (SELECT COALESCE((SELECT id FROM pet WHERE name='Lua'), 0)) + 7),
        ((SELECT COALESCE((SELECT id FROM event WHERE description='Feira anual de adoção'), 0) + 8), (SELECT COALESCE((SELECT id FROM pet WHERE name='Lua'), 0)) + 8),
        ((SELECT COALESCE((SELECT id FROM event WHERE description='Feira anual de adoção'), 0) + 9), (SELECT COALESCE((SELECT id FROM pet WHERE name='Lua'), 0)) + 9),
        ((SELECT COALESCE((SELECT id FROM event WHERE description='Feira anual de adoção'), 0) + 9), (SELECT COALESCE((SELECT id FROM pet WHERE name='Lua'), 0)) + 10),
        ((SELECT COALESCE((SELECT id FROM event WHERE description='Feira anual de adoção'), 0) + 9), (SELECT COALESCE((SELECT id FROM pet WHERE name='Lua'), 0)) + 11),
        ((SELECT COALESCE((SELECT id FROM event WHERE description='Feira anual de adoção'), 0) + 10), (SELECT COALESCE((SELECT id FROM pet WHERE name='Lua'), 0)) + 12),
        ((SELECT COALESCE((SELECT id FROM event WHERE description='Feira anual de adoção'), 0) + 10), (SELECT COALESCE((SELECT id FROM pet WHERE name='Lua'), 0)) + 13),
        ((SELECT COALESCE((SELECT id FROM event WHERE description='Feira anual de adoção'), 0) + 10), (SELECT COALESCE((SELECT id FROM pet WHERE name='Lua'), 0)) + 14),
        ((SELECT COALESCE((SELECT id FROM event WHERE description='Feira anual de adoção'), 0) + 11), (SELECT COALESCE((SELECT id FROM pet WHERE name='Lua'), 0)) + 15),
        ((SELECT COALESCE((SELECT id FROM event WHERE description='Feira anual de adoção'), 0) + 11), (SELECT COALESCE((SELECT id FROM pet WHERE name='Lua'), 0)) + 16),
        ((SELECT COALESCE((SELECT id FROM event WHERE description='Feira anual de adoção'), 0) + 11), (SELECT COALESCE((SELECT id FROM pet WHERE name='Lua'), 0)) + 17),
        ((SELECT COALESCE((SELECT id FROM event WHERE description='Feira anual de adoção'), 0) + 12), (SELECT COALESCE((SELECT id FROM pet WHERE name='Lua'), 0)) + 18),
        ((SELECT COALESCE((SELECT id FROM event WHERE description='Feira anual de adoção'), 0) + 12), (SELECT COALESCE((SELECT id FROM pet WHERE name='Lua'), 0)) + 19),
        ((SELECT COALESCE((SELECT id FROM event WHERE description='Feira anual de adoção'), 0) + 12), (SELECT COALESCE((SELECT id FROM pet WHERE name='Lua'), 0)) + 20),
        ((SELECT COALESCE((SELECT id FROM event WHERE description='Feira anual de adoção'), 0) + 13), (SELECT COALESCE((SELECT id FROM pet WHERE name='Lua'), 0)) + 18),
        ((SELECT COALESCE((SELECT id FROM event WHERE description='Feira anual de adoção'), 0) + 13), (SELECT COALESCE((SELECT id FROM pet WHERE name='Lua'), 0)) + 19),
        ((SELECT COALESCE((SELECT id FROM event WHERE description='Feira anual de adoção'), 0) + 13), (SELECT COALESCE((SELECT id FROM pet WHERE name='Lua'), 0)) + 20),
        ((SELECT COALESCE((SELECT id FROM event WHERE description='Feira anual de adoção'), 0) + 14), (SELECT COALESCE((SELECT id FROM pet WHERE name='Lua'), 0)) + 3),
        ((SELECT COALESCE((SELECT id FROM event WHERE description='Feira anual de adoção'), 0) + 14), (SELECT COALESCE((SELECT id FROM pet WHERE name='Lua'), 0)) + 4),
        ((SELECT COALESCE((SELECT id FROM event WHERE description='Feira anual de adoção'), 0) + 14), (SELECT COALESCE((SELECT id FROM pet WHERE name='Lua'), 0)) + 5),
        ((SELECT COALESCE((SELECT id FROM event WHERE description='Feira anual de adoção'), 0) + 15), (SELECT COALESCE((SELECT id FROM pet WHERE name='Lua'), 0)) + 6),
        ((SELECT COALESCE((SELECT id FROM event WHERE description='Feira anual de adoção'), 0) + 15), (SELECT COALESCE((SELECT id FROM pet WHERE name='Lua'), 0)) + 7),
        ((SELECT COALESCE((SELECT id FROM event WHERE description='Feira anual de adoção'), 0) + 15), (SELECT COALESCE((SELECT id FROM pet WHERE name='Lua'), 0)) + 8),
        ((SELECT COALESCE((SELECT id FROM event WHERE description='Feira anual de adoção'), 0) + 16), (SELECT COALESCE((SELECT id FROM pet WHERE name='Lua'), 0)) + 9),
        ((SELECT COALESCE((SELECT id FROM event WHERE description='Feira anual de adoção'), 0) + 16), (SELECT COALESCE((SELECT id FROM pet WHERE name='Lua'), 0)) + 10),
        ((SELECT COALESCE((SELECT id FROM event WHERE description='Feira anual de adoção'), 0) + 16), (SELECT COALESCE((SELECT id FROM pet WHERE name='Lua'), 0)) + 11),
        ((SELECT COALESCE((SELECT id FROM event WHERE description='Feira anual de adoção'), 0) + 17), (SELECT COALESCE((SELECT id FROM pet WHERE name='Lua'), 0)) + 12),
        ((SELECT COALESCE((SELECT id FROM event WHERE description='Feira anual de adoção'), 0) + 17), (SELECT COALESCE((SELECT id FROM pet WHERE name='Lua'), 0)) + 13),
        ((SELECT COALESCE((SELECT id FROM event WHERE description='Feira anual de adoção'), 0) + 17), (SELECT COALESCE((SELECT id FROM pet WHERE name='Lua'), 0)) + 14),
        ((SELECT COALESCE((SELECT id FROM event WHERE description='Feira anual de adoção'), 0) + 18), (SELECT COALESCE((SELECT id FROM pet WHERE name='Lua'), 0)) + 15),
        ((SELECT COALESCE((SELECT id FROM event WHERE description='Feira anual de adoção'), 0) + 18), (SELECT COALESCE((SELECT id FROM pet WHERE name='Lua'), 0)) + 16),
        ((SELECT COALESCE((SELECT id FROM event WHERE description='Feira anual de adoção'), 0) + 18), (SELECT COALESCE((SELECT id FROM pet WHERE name='Lua'), 0)) + 17),
        ((SELECT COALESCE((SELECT id FROM event WHERE description='Feira anual de adoção'), 0) + 19), (SELECT COALESCE((SELECT id FROM pet WHERE name='Lua'), 0)) + 18),
        ((SELECT COALESCE((SELECT id FROM event WHERE description='Feira anual de adoção'), 0) + 19), (SELECT COALESCE((SELECT id FROM pet WHERE name='Lua'), 0)) + 19),
        ((SELECT COALESCE((SELECT id FROM event WHERE description='Feira anual de adoção'), 0) + 19), (SELECT COALESCE((SELECT id FROM pet WHERE name='Lua'), 0)) + 20),
        ((SELECT COALESCE((SELECT id FROM event WHERE description='Feira anual de adoção'), 0) + 20), (SELECT COALESCE((SELECT id FROM pet WHERE name='Lua'), 0)) + 9),
        ((SELECT COALESCE((SELECT id FROM event WHERE description='Feira anual de adoção'), 0) + 20), (SELECT COALESCE((SELECT id FROM pet WHERE name='Lua'), 0)) + 10),
        ((SELECT COALESCE((SELECT id FROM event WHERE description='Feira anual de adoção'), 0) + 20), (SELECT COALESCE((SELECT id FROM pet WHERE name='Lua'), 0)) + 11),
        ((SELECT COALESCE((SELECT id FROM event WHERE description='Feira anual de adoção'), 0) + 21), (SELECT COALESCE((SELECT id FROM pet WHERE name='Lua'), 0)) + 12),
        ((SELECT COALESCE((SELECT id FROM event WHERE description='Feira anual de adoção'), 0) + 21), (SELECT COALESCE((SELECT id FROM pet WHERE name='Lua'), 0)) + 13),
        ((SELECT COALESCE((SELECT id FROM event WHERE description='Feira anual de adoção'), 0) + 21), (SELECT COALESCE((SELECT id FROM pet WHERE name='Lua'), 0)) + 14),
        ((SELECT COALESCE((SELECT id FROM event WHERE description='Feira anual de adoção'), 0) + 22), (SELECT COALESCE((SELECT id FROM pet WHERE name='Lua'), 0)) + 15),
        ((SELECT COALESCE((SELECT id FROM event WHERE description='Feira anual de adoção'), 0) + 22), (SELECT COALESCE((SELECT id FROM pet WHERE name='Lua'), 0)) + 16),
        ((SELECT COALESCE((SELECT id FROM event WHERE description='Feira anual de adoção'), 0) + 22), (SELECT COALESCE((SELECT id FROM pet WHERE name='Lua'), 0)) + 17),
        ((SELECT COALESCE((SELECT id FROM event WHERE description='Feira anual de adoção'), 0) + 23), (SELECT COALESCE((SELECT id FROM pet WHERE name='Lua'), 0)) + 18),
        ((SELECT COALESCE((SELECT id FROM event WHERE description='Feira anual de adoção'), 0) + 23), (SELECT COALESCE((SELECT id FROM pet WHERE name='Lua'), 0)) + 19),
        ((SELECT COALESCE((SELECT id FROM event WHERE description='Feira anual de adoção'), 0) + 23), (SELECT COALESCE((SELECT id FROM pet WHERE name='Lua'), 0)) + 20);

INSERT INTO event_image (event_id, image, order_number)
VALUES ((SELECT COALESCE((SELECT id FROM event WHERE description='Feira anual de adoção'), 0)), 'media/event_images/event.jpg', 0),
       ((SELECT COALESCE((SELECT id FROM event WHERE description='Feira anual de adoção'), 0)), 'media/event_images/event1.jpg', 1),
       ((SELECT COALESCE((SELECT id FROM event WHERE description='Feira anual de adoção'), 0)), 'media/event_images/event2.jpg', 2),
       ((SELECT COALESCE((SELECT id FROM event WHERE description='Feira anual de adoção'), 0) + 1), 'media/event_images/event3.jpg', 0),
       ((SELECT COALESCE((SELECT id FROM event WHERE description='Feira anual de adoção'), 0) + 2), 'media/event_images/event4.jpg', 0),
       ((SELECT COALESCE((SELECT id FROM event WHERE description='Feira anual de adoção'), 0) + 3), 'media/event_images/event5.jpg', 0),
       ((SELECT COALESCE((SELECT id FROM event WHERE description='Feira anual de adoção'), 0) + 4), 'media/event_images/event6.jpg', 0),
       ((SELECT COALESCE((SELECT id FROM event WHERE description='Feira anual de adoção'), 0) + 5), 'media/event_images/event7.jpg', 0),
       ((SELECT COALESCE((SELECT id FROM event WHERE description='Feira anual de adoção'), 0) + 6), 'media/event_images/event8.jpg', 0),
       ((SELECT COALESCE((SELECT id FROM event WHERE description='Feira anual de adoção'), 0) + 7), 'media/event_images/event9.jpg', 0),
       ((SELECT COALESCE((SELECT id FROM event WHERE description='Feira anual de adoção'), 0) + 8), 'media/event_images/event10.jpg', 0),
       ((SELECT COALESCE((SELECT id FROM event WHERE description='Feira anual de adoção'), 0) + 9), 'media/event_images/event11.jpg', 0),
       ((SELECT COALESCE((SELECT id FROM event WHERE description='Feira anual de adoção'), 0) + 10), 'media/event_images/event12.jpg', 0),
       ((SELECT COALESCE((SELECT id FROM event WHERE description='Feira anual de adoção'), 0) + 11), 'media/event_images/event13.jpg', 0),
       ((SELECT COALESCE((SELECT id FROM event WHERE description='Feira anual de adoção'), 0) + 12), 'media/event_images/event14.jpg', 0),
       ((SELECT COALESCE((SELECT id FROM event WHERE description='Feira anual de adoção'), 0) + 13), 'media/event_images/event15.jpg', 0),
       ((SELECT COALESCE((SELECT id FROM event WHERE description='Feira anual de adoção'), 0) + 14), 'media/event_images/event16.jpg', 0),
       ((SELECT COALESCE((SELECT id FROM event WHERE description='Feira anual de adoção'), 0) + 15), 'media/event_images/event17.jpg', 0),
       ((SELECT COALESCE((SELECT id FROM event WHERE description='Feira anual de adoção'), 0) + 16), 'media/event_images/event18.jpg', 0),
       ((SELECT COALESCE((SELECT id FROM event WHERE description='Feira anual de adoção'), 0) + 17), 'media/event_images/event19.jpg', 0),
       ((SELECT COALESCE((SELECT id FROM event WHERE description='Feira anual de adoção'), 0) + 18), 'media/event_images/event20.jpg', 0),
       ((SELECT COALESCE((SELECT id FROM event WHERE description='Feira anual de adoção'), 0) + 19), 'media/event_images/event21.jpg', 0),
       ((SELECT COALESCE((SELECT id FROM event WHERE description='Feira anual de adoção'), 0) + 20), 'media/event_images/event22.jpg', 0),
       ((SELECT COALESCE((SELECT id FROM event WHERE description='Feira anual de adoção'), 0) + 21), 'media/event_images/event23.jpg', 0),
       ((SELECT COALESCE((SELECT id FROM event WHERE description='Feira anual de adoção'), 0) + 22), 'media/event_images/event24.jpg', 0),
       ((SELECT COALESCE((SELECT id FROM event WHERE description='Feira anual de adoção'), 0) + 23), 'media/event_images/event25.jpg', 0);

INSERT INTO favorite_pet (user_id, pet_id)
VALUES ((SELECT COALESCE((SELECT id FROM custom_user WHERE name='Ana Maria Rosa'), 0)), (SELECT COALESCE((SELECT id FROM pet WHERE name='Lua'), 0))),
        ((SELECT COALESCE((SELECT id FROM custom_user WHERE name='Ana Maria Rosa'), 0)), (SELECT COALESCE((SELECT id FROM pet WHERE name='Lua'), 0) + 1)),
        ((SELECT COALESCE((SELECT id FROM custom_user WHERE name='Ana Maria Rosa'), 0)), (SELECT COALESCE((SELECT id FROM pet WHERE name='Lua'), 0) + 2)),
        ((SELECT COALESCE((SELECT id FROM custom_user WHERE name='Ana Maria Rosa'), 0)), (SELECT COALESCE((SELECT id FROM pet WHERE name='Lua'), 0) + 3)),
        ((SELECT COALESCE((SELECT id FROM custom_user WHERE name='Ana Maria Rosa'), 0)), (SELECT COALESCE((SELECT id FROM pet WHERE name='Lua'), 0) + 4)),
        ((SELECT COALESCE((SELECT id FROM custom_user WHERE name='Ana Maria Rosa'), 0)), (SELECT COALESCE((SELECT id FROM pet WHERE name='Lua'), 0) + 5)),
        ((SELECT COALESCE((SELECT id FROM custom_user WHERE name='Ana Maria Rosa'), 0)), (SELECT COALESCE((SELECT id FROM pet WHERE name='Lua'), 0) + 6)),
        ((SELECT COALESCE((SELECT id FROM custom_user WHERE name='Ana Maria Rosa'), 0) + 1), (SELECT COALESCE((SELECT id FROM pet WHERE name='Lua'), 0))),
        ((SELECT COALESCE((SELECT id FROM custom_user WHERE name='Ana Maria Rosa'), 0) + 1), (SELECT COALESCE((SELECT id FROM pet WHERE name='Lua'), 0) + 1)),
        ((SELECT COALESCE((SELECT id FROM custom_user WHERE name='Ana Maria Rosa'), 0) + 1), (SELECT COALESCE((SELECT id FROM pet WHERE name='Lua'), 0) + 2)),
        ((SELECT COALESCE((SELECT id FROM custom_user WHERE name='Ana Maria Rosa'), 0) + 1), (SELECT COALESCE((SELECT id FROM pet WHERE name='Lua'), 0) + 3)),
        ((SELECT COALESCE((SELECT id FROM custom_user WHERE name='Ana Maria Rosa'), 0) + 1), (SELECT COALESCE((SELECT id FROM pet WHERE name='Lua'), 0) + 4)),
        ((SELECT COALESCE((SELECT id FROM custom_user WHERE name='Ana Maria Rosa'), 0) + 1), (SELECT COALESCE((SELECT id FROM pet WHERE name='Lua'), 0) + 5)),
        ((SELECT COALESCE((SELECT id FROM custom_user WHERE name='Ana Maria Rosa'), 0) + 1), (SELECT COALESCE((SELECT id FROM pet WHERE name='Lua'), 0) + 6)),
        ((SELECT COALESCE((SELECT id FROM custom_user WHERE name='Ana Maria Rosa'), 0) + 2), (SELECT COALESCE((SELECT id FROM pet WHERE name='Lua'), 0))),
        ((SELECT COALESCE((SELECT id FROM custom_user WHERE name='Ana Maria Rosa'), 0) + 2), (SELECT COALESCE((SELECT id FROM pet WHERE name='Lua'), 0) + 1)),
        ((SELECT COALESCE((SELECT id FROM custom_user WHERE name='Ana Maria Rosa'), 0) + 2), (SELECT COALESCE((SELECT id FROM pet WHERE name='Lua'), 0) + 2));

INSERT INTO favorite_event (user_id, event_id)
VALUES ((SELECT COALESCE((SELECT id FROM custom_user WHERE name='Ana Maria Rosa'), 0)), (SELECT COALESCE((SELECT id FROM event WHERE description='Feira anual de adoção'), 0))),
       ((SELECT COALESCE((SELECT id FROM custom_user WHERE name='Ana Maria Rosa'), 0)), (SELECT COALESCE((SELECT id FROM event WHERE description='Feira anual de adoção'), 0) + 1)),
       ((SELECT COALESCE((SELECT id FROM custom_user WHERE name='Ana Maria Rosa'), 0)), (SELECT COALESCE((SELECT id FROM event WHERE description='Feira anual de adoção'), 0) + 2)),
       ((SELECT COALESCE((SELECT id FROM custom_user WHERE name='Ana Maria Rosa'), 0)), (SELECT COALESCE((SELECT id FROM event WHERE description='Feira anual de adoção'), 0) + 3)),
       ((SELECT COALESCE((SELECT id FROM custom_user WHERE name='Ana Maria Rosa'), 0)), (SELECT COALESCE((SELECT id FROM event WHERE description='Feira anual de adoção'), 0) + 4)),
       ((SELECT COALESCE((SELECT id FROM custom_user WHERE name='Ana Maria Rosa'), 0)), (SELECT COALESCE((SELECT id FROM event WHERE description='Feira anual de adoção'), 0) + 5)),
       ((SELECT COALESCE((SELECT id FROM custom_user WHERE name='Ana Maria Rosa'), 0)), (SELECT COALESCE((SELECT id FROM event WHERE description='Feira anual de adoção'), 0) + 6)),
       ((SELECT COALESCE((SELECT id FROM custom_user WHERE name='Ana Maria Rosa'), 0) + 1), (SELECT COALESCE((SELECT id FROM event WHERE description='Feira anual de adoção'), 0))),
       ((SELECT COALESCE((SELECT id FROM custom_user WHERE name='Ana Maria Rosa'), 0) + 1), (SELECT COALESCE((SELECT id FROM event WHERE description='Feira anual de adoção'), 0) + 1)),
       ((SELECT COALESCE((SELECT id FROM custom_user WHERE name='Ana Maria Rosa'), 0) + 1), (SELECT COALESCE((SELECT id FROM event WHERE description='Feira anual de adoção'), 0) + 2)),
       ((SELECT COALESCE((SELECT id FROM custom_user WHERE name='Ana Maria Rosa'), 0) + 1), (SELECT COALESCE((SELECT id FROM event WHERE description='Feira anual de adoção'), 0) + 3)),
       ((SELECT COALESCE((SELECT id FROM custom_user WHERE name='Ana Maria Rosa'), 0) + 1), (SELECT COALESCE((SELECT id FROM event WHERE description='Feira anual de adoção'), 0) + 4)),
       ((SELECT COALESCE((SELECT id FROM custom_user WHERE name='Ana Maria Rosa'), 0) + 1), (SELECT COALESCE((SELECT id FROM event WHERE description='Feira anual de adoção'), 0) + 5)),
       ((SELECT COALESCE((SELECT id FROM custom_user WHERE name='Ana Maria Rosa'), 0) + 1), (SELECT COALESCE((SELECT id FROM event WHERE description='Feira anual de adoção'), 0) + 6)),
       ((SELECT COALESCE((SELECT id FROM custom_user WHERE name='Ana Maria Rosa'), 0) + 2), (SELECT COALESCE((SELECT id FROM event WHERE description='Feira anual de adoção'), 0))),
       ((SELECT COALESCE((SELECT id FROM custom_user WHERE name='Ana Maria Rosa'), 0) + 2), (SELECT COALESCE((SELECT id FROM event WHERE description='Feira anual de adoção'), 0) + 1)),
       ((SELECT COALESCE((SELECT id FROM custom_user WHERE name='Ana Maria Rosa'), 0) + 2), (SELECT COALESCE((SELECT id FROM event WHERE description='Feira anual de adoção'), 0) + 2));
