# Generated by Django 5.0.3 on 2024-03-12 21:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='type',
            field=models.IntegerField(choices=[(1, 'member'), (2, 'protector'), (3, 'sponsor')], default=1),
        ),
    ]
