# Generated by Django 5.0.3 on 2024-04-18 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0013_customuser_last_login_attempt_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='login_attempts',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
