name: Django CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-20.04
    env:
      SECRET_KEY: ${{ secrets.SECRET_KEY }}
      DB_ENGINE: ${{ secrets.DB_ENGINE }}
      DB_NAME: ${{ secrets.DB_NAME }}
      DB_USER: ${{ secrets.DB_USER }}
      DB_PASSWORD: ${{ secrets.DB_PASSWORD }}
      DB_HOST: localhost
      DB_PORT: ${{ secrets.DB_PORT }}
      EMAIL_HOST_USER: ${{ secrets.EMAIL_HOST_USER }}
      EMAIL_HOST_PASSWORD: ${{ secrets.EMAIL_HOST_PASSWORD }}
    strategy:
      max-parallel: 4
      matrix:
        python-version: [3.12.1]
    services:
      postgres:
        image: postgres:15.6
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: conexaopet_db
        ports:
          - 5432:5432
        options: --health-cmd pg_isready --health-interval 10s --health-timeout 5s --health-retries 5

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
    - name: psycopg2 prerequisites
      run: sudo apt-get install -y libpq-dev
    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    - name: Apply Migrations and Collect Static Files
      run: |
        python manage.py migrate
        python manage.py collectstatic --noinput
    - name: Run Tests
      run: |
        python manage.py test

  deploy:
    name: Deploying
    needs: [test]
    runs-on: ubuntu-20.04
    env:
      EC2_HOST_DNS: ${{ secrets.EC2_HOST_DNS }}
      SECRET_KEY: ${{ secrets.SECRET_KEY }}
      DB_ENGINE: ${{ secrets.DB_ENGINE }}
      DB_NAME: ${{ secrets.DB_NAME }}
      DB_USER: ${{ secrets.DB_USER }}
      DB_PASSWORD: ${{ secrets.DB_PASSWORD }}
      DB_HOST: ${{ secrets.DB_HOST}}
      DB_PORT: ${{ secrets.DB_PORT }}
      EMAIL_HOST_USER: ${{ secrets.EMAIL_HOST_USER }}
      EMAIL_HOST_PASSWORD: ${{ secrets.EMAIL_HOST_PASSWORD }}
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install awscli
        sudo apt-get update && sudo apt-get install -y jq
    - name: Create .env file
      run: touch .env
    - name: Get secrets from GitHub
      run: |
        echo "SECRET_KEY=$(curl -s -H 'Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}' https://api.github.com/repos/${{ github.repository }}/actions/secrets/SECRET_KEY | jq -r .secret)" >> .env
        echo "DEBUG=$(curl -s -H 'Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}' https://api.github.com/repos/${{ github.repository }}/actions/secrets/DEBUG | jq -r .secret)" >> .env
        echo "DB_ENGINE=$(curl -s -H 'Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}' https://api.github.com/repos/${{ github.repository }}/actions/secrets/DB_ENGINE | jq -r .secret)" >> .env
        echo "DB_HOST=$(curl -s -H 'Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}' https://api.github.com/repos/${{ github.repository }}/actions/secrets/DB_HOST | jq -r .secret)" >> .env
        echo "DB_NAME=$(curl -s -H 'Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}' https://api.github.com/repos/${{ github.repository }}/actions/secrets/DB_NAME | jq -r .secret)" >> .env
        echo "DB_PASSWORD=$(curl -s -H 'Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}' https://api.github.com/repos/${{ github.repository }}/actions/secrets/DB_PASSWORD | jq -r .secret)" >> .env
        echo "DB_PORT=$(curl -s -H 'Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}' https://api.github.com/repos/${{ github.repository }}/actions/secrets/DB_PORT | jq -r .secret)" >> .env
        echo "DB_USER=$(curl -s -H 'Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}' https://api.github.com/repos/${{ github.repository }}/actions/secrets/DB_USER | jq -r .secret)" >> .env
        echo "EC2_HOST_DNS=$(curl -s -H 'Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}' https://api.github.com/repos/${{ github.repository }}/actions/secrets/EC2_HOST_DNS | jq -r .secret)" >> .env
        echo "EC2_SSH_KEY_PEM=$(curl -s -H 'Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}' https://api.github.com/repos/${{ github.repository }}/actions/secrets/EC2_SSH_KEY_PEM | jq -r .secret)" >> .env
        echo "EC2_USERNAME=$(curl -s -H 'Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}' https://api.github.com/repos/${{ github.repository }}/actions/secrets/EC2_USERNAME | jq -r .secret)" >> .env
        echo "EMAIL_HOST_USER=$(curl -s -H 'Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}' https://api.github.com/repos/${{ github.repository }}/actions/secrets/EMAIL_HOST_USER | jq -r .secret)" >> .env
        echo "EMAIL_HOST_PASSWORD=$(curl -s -H 'Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}' https://api.github.com/repos/${{ github.repository }}/actions/secrets/EMAIL_HOST_PASSWORD | jq -r .secret)" >> .env
        echo "STATICFILES=$(curl -s -H 'Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}' https://api.github.com/repos/${{ github.repository }}/actions/secrets/STATICFILES | jq -r .secret)" >> .env
        echo "MEDIAFILES=$(curl -s -H 'Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}' https://api.github.com/repos/${{ github.repository }}/actions/secrets/MEDIAFILES | jq -r .secret)" >> .env
        echo "ACCESS_TOKEN_LIFETIME=$(curl -s -H 'Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}' https://api.github.com/repos/${{ github.repository }}/actions/secrets/ACCESS_TOKEN_LIFETIME | jq -r .secret)" >> .env
        echo "REFRESH_TOKEN_LIFETIME=$(curl -s -H 'Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}' https://api.github.com/repos/${{ github.repository }}/actions/secrets/REFRESH_TOKEN_LIFETIME | jq -r .secret)" >> .env
        echo "DJANGO_SETTINGS_MODULE=$(curl -s -H 'Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}' https://api.github.com/repos/${{ github.repository }}/actions/secrets/DJANGO_SETTINGS_MODULE | jq -r .secret)" >> .env

    - name: Install docker on EC2
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.EC2_HOST_DNS }}
        username: ${{ secrets.EC2_USERNAME }}
        key: ${{ secrets.EC2_SSH_KEY_PEM }}
        script: |
            sudo su
            sudo apt-get update
            yes | sudo apt-get install docker.io
            sudo systemctl start docker
            sudo systemctl enable docker
            sudo usermod -aG docker $USER
            sudo usermod -aG docker ubuntu
            exec bash
    - name: Install docker-compose on EC2
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.EC2_HOST_DNS }}
        username: ${{ secrets.EC2_USERNAME }}
        key: ${{ secrets.EC2_SSH_KEY_PEM }}
        script: |
            sudo su
            sudo curl -L "https://github.com/docker/compose/releases/latest/download/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
            sudo chmod +x /usr/local/bin/docker-compose
            docker-compose --version
    - name: Deploying Application
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.EC2_HOST_DNS }}
        username: ${{ secrets.EC2_USERNAME }}
        key: ${{ secrets.EC2_SSH_KEY_PEM }}
        script: |
            sudo su
            docker stop conexaopet_web conexaopet_app conexaopet_db
            docker rm conexaopet_web conexaopet_app conexaopet_db
            rm -rf conexaopet-api
            git clone https://github.com/carolahn/conexaopet-api.git
            mv .env conexaopet-api/
            # conectar-se à instância EC2 
            # $ ssh -i "myapp-express-keys.pem" ubuntu@ec2-52-91-212-72.compute-1.amazonaws.com
            $ cd conexaopet-api
            # $ sudo su
            # # apt install vim
            # # vim .env
            # Colar o conteúdo de .env.example
            docker-compose -f docker-compose.yml up --build